#!/bin/sh

device=$1

if [ -z "$device" ]; then
    echo "Usage:\nresetpi <device>"
    exit 1 
else
    echo "Device $device"
fi

. scripts/create-image
. scripts/unpack-initrd
. scripts/build-flashback
. scripts/extract-deb

# Initialize the environment
init_env
cd build

write_image_device $device

# Get the  writable partition and rename to restore
restore="$(findfs LABEL=writable)"
tune2fs -L restore "$restore"

# Generate the name of the new writable partition
writable="${device}3"
if [ $device = *"mmc"* ]; then 
    writable="${device}p2"
fi

# Create the new writable partition with free space
create_new_writable $device $writable

# Move the writable data to the new partition
move_to_writable $restore $writable

# Unpack the initrd image
unpack_initrd

# Build flashback and add it to initrd/bin
build_flashback

# Extract the extra tools we need
extract_deb_files

